In [1]:
import numpy as np

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [3]:
#criando um array 1D
l = [1,2,3]
x = np.array(l)
print('X = ', x)
print('Shape = ', x.shape)

X =  [1 2 3]
Shape =  (3,)


In [4]:
type(x)

numpy.ndarray

In [8]:
#criando um array 2D
l = [[1,2],[3,4]]
x = np.array(l)
print('X = \n', x)
print('Shape = ', x.shape)

X = 
 [[1 2]
 [3 4]]
Shape =  (2, 2)


In [9]:
type(x)

numpy.ndarray

In [10]:
#criando um array 3D
l = [[1,2,3],[4,5,6],[6,7,8]]
x = np.array(l)
print('X = \n', x)
print('Shape = ', x.shape)

X = 
 [[1 2 3]
 [4 5 6]
 [6 7 8]]
Shape =  (3, 3)


In [11]:
#utilizando a função np.zeros
dim = (2,2) #(linhas, colunas)
x = np.zeros(dim) #irá criar uma matriz com todos os elementos de valor igual a 0
print('X =\n', x)
print('Shape = ', x.shape)


X =
 [[0. 0.]
 [0. 0.]]
Shape =  (2, 2)


In [12]:
#utilizando a função np.ones
z = (2,2)
x = np.ones(z) #irá criar uma matriz com todos os elementos de valor igual a 1
print('X =\n', x)
print('Shape = ', x.shape)

X =
 [[1. 1.]
 [1. 1.]]
Shape =  (2, 2)


In [14]:
#conhecendo a função linspace
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [20]:
#criando valores dentro de um intervalo
min, max = 1, 60 #considerando um intervalo de números de 0 a 60
x = np.linspace(min,max, num=6, dtype=int)#conforme as variáveis min e max, será
#considerado os valores dentro do intervalo, com 6 números do tipo inteiro
print('X = ', x)
print('Shape = ', x.shape)

X =  [ 1 12 24 36 48 60]
Shape =  (6,)


In [22]:
#criando matriz identidade com o np.eye
n = 10
x = np.eye(n) #para o np.eye basta informar um número inteiro
print('X =\n', x)
print('Shape = ', x.shape)

X =
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Shape =  (10, 10)


In [29]:
#criando valores aleatório
x = np.random.random(size=(2,4))#definido um array de 2 linhas e 4 colunas
print('X =\n', x)

X =
 [[0.31721792 0.00977213 0.75172888 0.61962074]
 [0.60594494 0.65109351 0.85708017 0.00108544]]
