In [2]:
#criando um array através do linspace
import numpy as np
x = np.linspace(10, 100, 10, dtype=int) #de 10 a 100, intervalo de 10 e inteiros
print('X:\n', x)

X:
 [ 10  20  30  40  50  60  70  80  90 100]


In [5]:
#exibindo os elementos
print('X:\n', x)
print('O primeiro elemento é: ', x[0])
print('O segundo elemento é: ', x[1])#sempre considerando como índice n-1
print('O último elemento é: ', x[-1])#índice negativo percorre o array em sentido contrário 

X:
 [ 10  20  30  40  50  60  70  80  90 100]
O primeiro elemento é:  10
O segundo elemento é:  20
O último elemento é:  100


In [8]:
  #utilizando slicing para extração
  print('X:\n', x)
  print('Os dois primeiros elementos são: ', x[0:2])#lembrando que para o slicing, o último elemento do índice não é considerado
  print('Os dois primeiros elementos são: ', x[:2])#não informando o primeiro elemento é considerado como 0
  print('Os dois últimos elementos são: ',x[-2:])

X:
 [ 10  20  30  40  50  60  70  80  90 100]
Os dois primeiros elementos são:  [10 20]
Os dois primeiros elementos são:  [10 20]
Os dois últimos elementos são:  [ 90 100]


In [15]:
#utilizando o slicing em matriz 2D
x = x.reshape(2,5) #utilizando o método reshape para criar uma matriz com 2 linhas e 5 colunas
print('X:\n', x)

X:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [19]:
#extraindo os valores da matriz 2D
print('O primeiro valor é: ', x[0,0])
print('O terceiro valor é: ', x[0,2])
print('O último valor é: ', x[1,4])

O primeiro valor é:  10
O terceiro valor é:  30
O último valor é:  100


In [33]:
#extaindo subarrays de matriz 2D
print('A primeira linha é: ', x[0, 0:])
print('A segunda linha é: ', x[1, 0:])
print('A primeira coluna é: ',x[0:, 0])
print('A quarta coluna é:\n', x[: ,[3]])#para manter uma formatação de coluna, utiliza-se os colchetes

A primeira linha é:  [10 20 30 40 50]
A segunda linha é:  [ 60  70  80  90 100]
A primeira coluna é:  [10 60]
A quarta coluna é:
 [[40]
 [90]]


In [37]:
#cuidados com compartilhamento de subarrays
x = np.array([1,2,3])
print('X = ', x)
y = x[:2]
print('Y = ', y)
y[0]=-4 #alterando o valor do índice 0 da matriz y
print('Nova matriz:\nY = ', y)
print('Conferindo a matriz X\nX = ', x)#ao alterar a matriz Y, alterou-se também a matriz X porque o slicing é um compartilhamento de memória

X =  [1 2 3]
Y =  [1 2]
Nova matriz:
Y =  [-4  2]
Conferindo a matriz X
X =  [-4  2  3]


In [38]:
#utilizando o método .copy
y = x[:2].copy()#com esta função, não haverá compartilhamento de memória
print('Matriz X:\nX = ', x)
print('Matriz Y:\nY = ', y)
y[0] = -100
print('Nova matriz Y:\n Y = ', y)
print('Checando a matriz X:\nX = ', x)#com o .copy não houve alteração na matriz X

Matriz X:
X =  [-4  2  3]
Matriz Y:
Y =  [-4  2]
Nova matriz Y:
 Y =  [-100    2]
Checando a matriz X:
X =  [-4  2  3]
