In [2]:
  import numpy as np
  x = np.array([[1,2],[3,4]])
  y = np.array([[1.5],[3.5]])
  print('x:\n', x)
  print('y:\n', y)

x:
 [[1 2]
 [3 4]]
y:
 [[1.5]
 [3.5]]


In [5]:
#comparação entre arrays
print('Comparação de um array escalar (>):\n', x > 2)#x é maior do que 2?
print('Comparação de um array escalar (<):\n', x < 2)#x é menor do que 2?
print('Comparação de um array escalar (==):\n', x == 2)#x é igual a 2?
print('Comparação de um array escalar (>=):\n', x >= 2)#x é maior ou igual a 2?
print('Comparação de um array escalar (<=):\n', x <= 2)#x é menor ou igual a 2?
print('Comparação de um array escalar com ele mesmo (==):\n', x==x)#x é igual a x?
print('Comparação entre os arrays X e Y (>=):\n', x >= y)#x é maior ou igual a y?

Comparação de um array escalar (>):
 [[False False]
 [ True  True]]
Comparação de um array escalar (<):
 [[ True False]
 [False False]]
Comparação de um array escalar (==):
 [[False  True]
 [False False]]
Comparação de um array escalar (>=):
 [[False  True]
 [ True  True]]
Comparação de um array escalar (<=):
 [[ True  True]
 [False False]]
Comparação de um array escalar com ele mesmo (==):
 [[ True  True]
 [ True  True]]
Comparação entre os arrays X e Y (>=):
 [[False  True]
 [False  True]]


In [8]:
#indexação booleana
x = np.array([[1,2,3],
              [4,8,0],
              [8,4,2]])
print('x:\n', x)

x:
 [[1 2 3]
 [4 8 0]
 [8 4 2]]


In [13]:
'''indexação booleana para retornar elementos
maiores do que K'''
k = 5
cond = x > k #condição: x maior que k (5)
print('Condição:\n', cond)
print('Elementos maiores que k:\n', x[cond])
print('Quantidade de elementos maiores do que k:\n', len(x[cond]))


Condição:
 [[False False False]
 [False  True False]
 [ True False False]]
Elementos maiores que k:
 [8 8]
Quantidade de elementos maiores do que k:
 2


In [15]:
#retornando os números pares
cond2 = (x % 2) == 0
print('Condição:\n', cond2)
print('Números pares:\n', x[cond2])
print('Quantidade de números pares:\n', len(x[cond2]))

Condição:
 [[False  True False]
 [ True  True  True]
 [ True  True  True]]
Números pares:
 [2 4 8 0 8 4 2]
Quantidade de números pares:
 7


In [18]:
#retornando os números ímpares
cond3 = (x % 2) == 1
print('Condição:\n', cond3)
print('Números ímpares:\n', x[cond3])
print('Quantidade de números ímpares:\n', len(x[cond3]))

Condição:
 [[ True False  True]
 [False False False]
 [False False False]]
Números ímpares:
 [1 3]
Quantidade de números ímpares:
 2
