In [2]:
#multiplicando os elementos
import numpy as np
x=np.eye(2)
y=np.ones((2,2))
print('X =\n', x)
print('Y =\n', y)
print('Multiplicando as duas matrizes, obtemos:\n', x*y)


X =
 [[1. 0.]
 [0. 1.]]
Y =
 [[1. 1.]
 [1. 1.]]
Multiplicando as duas matrizes, obtemos:
 [[1. 0.]
 [0. 1.]]


In [ ]:
#utilizando broadcasting
print('Multiplicando X por 2:\n', x*2)

Multiplicando X por 2:
 [[2. 0.]
 [0. 2.]]


In [ ]:
#multiplicação matricial
print('Multiplicação utilizando np.dot:\n', np.dot(x,y))
print('Multiplicação utilizando @:\n', x@y)
print('Multiplicação utilizando .dot:\n', x.dot(y))
#em todos os métodos obtivemos os mesmos valores

Multiplicação utilizando np.dot:
 [[1. 1.]
 [1. 1.]]
Multiplicação utilizando @:
 [[1. 1.]
 [1. 1.]]
Multiplicação utilizando .dot:
 [[1. 1.]
 [1. 1.]]


In [3]:
'''
utilizando os métodos para resolução das seguintes equações:
a + 2*b = 7
3*a - 2*b = -11
A solução matricial para este problema pode ser descrita como:
Ax = c, onde:
A = [[1, 2], [3,-2]] << valores da equação
c = [7, -11] << valores de igualdade das equações
x = [a, b] << valores que devemos descobrir
'''
#definindo o problema:
A = np.array([[1,2], [3,-2]])
c = np.array([[7], [-11]])
print('A =\n', A)
print('c =\n', c)

A =
 [[ 1  2]
 [ 3 -2]]
c =
 [[  7]
 [-11]]


In [5]:
'''
A solução para o problema, consiste em dividir o vetor resultado pela matriz A,
ou, multiplicar os resultados pela matriz A inversa (A^⁻1)
'''
x = np.dot(np.linalg.inv(A),c)
print('Os valores de A e de B correspondem a: ', x.ravel())

Os valores de A e de B correspondem a:  [-1.  4.]
