In [3]:
#definindo um array
import numpy as np
x = np.array([[9,76,98],
             [10,79,45],
             [32,90,1]])
print('x:\n', x)

x:
 [[ 9 76 98]
 [10 79 45]
 [32 90  1]]


In [9]:
#reshape
"""
o método reshape é utilizado para alterar a estrutura
de um array, conforme os parâmetros definidos.
foi definido x como sendo um array do tipo 3x3
iremos alterar a estrutura deste array para 9x1, mantendo
os valores originais com o método reshape
importante: não é possível executar o reshape caso seja 
definido uma matriz que não comporte todos os valores sem
espaços vazios, no caso acima, se fosse definido uma estrutura do tipo
8x1, ou, 10x1, por exemplo, seria retornado um erro
"""
print('Alterando a estrutura do array para 9x1:\n', x.reshape(9,1))

Alterando a estrutura do array para 9x1:
 [[ 9]
 [76]
 [98]
 [10]
 [79]
 [45]
 [32]
 [90]
 [ 1]]


In [12]:
#transposição de matriz
#transposição de matriz tem por objetivo transformar os valores em linha para valores em coluna

print('Transposição do array x:\n', x.T)

Transposição do array x:
 [[ 9 10 32]
 [76 79 90]
 [98 45  1]]


In [16]:
#np.sum - utilizado para realizar a soma em um dado eixo, ou, de todos os valores
print('Soma de todos os valores: ', np.sum(x))
print('Soma de todos os valores ao longo das colunas: ', np.sum(x, axis=0))
print('Soma de todos os valores ao longo das linhas: ', np.sum(x, axis=1))

Soma de todos os valores:  440
Soma de todos os valores ao longo das colunas:  [ 51 245 144]
Soma de todos os valores ao longo das linhas:  [183 134 123]


In [19]:
#np.mean - média
print('A média de todos os valores é: ', np.mean(x))
print('A média dos valores ao longo das linhas é: ', np.mean(x, axis=1))
print('A média dos valores ao longo das colunas é: ', np.mean(x, axis=0))

A média de todos os valores é:  48.888888888888886
A média dos valores ao longo das linhas é:  [61.         44.66666667 41.        ]
A média dos valores ao longo das colunas é:  [17.         81.66666667 48.        ]


In [23]:
#np.median - mediana
print('A mediana de todos os valores é: ', np.median(x))
print('A mediana dos valores ao longo das linhas é: ', np.median(x, axis=1))
print('A mediana dos valores ao longo das colunas é: ', np.median(x, axis=0))

A mediana de todos os valores é:  45.0
A mediana dos valores ao longo das linhas é:  [76. 45. 32.]
A mediana dos valores ao longo das colunas é:  [10. 79. 45.]


In [33]:
#np.where - retornar posições do array conforme a condição dada
cond = (x % 2) == 0 #identificar todos valores pares
print('Números pares do array: ', x[cond])
print('Visualizando a posição dos números pares:\n', cond)
i, j = np.where(cond)
print('Índices das linhas que contém números pares:\t', i)
print('Índices das colunas que contém números pares:\t', j)

Números pares do array:  [76 98 10 32 90]
Visualizando a posição dos números pares:
 [[False  True  True]
 [ True False False]
 [ True  True False]]
Índices das linhas que contém números pares:	 [0 0 1 2 2]
Índices das colunas que contém números pares:	 [1 2 0 0 1]
