In [2]:
#criando dois arrays
import numpy as np
x = np.ones((2,2))
y = np.eye(2)
print('X =\n', x)
print('Y =\n', y)

X =
 [[1. 1.]
 [1. 1.]]
Y =
 [[1. 0.]
 [0. 1.]]


In [5]:
#soma
print('A soma das duas matrizes é:\n', x+y)
print('A soma com elementos tipo float é:\n ', (x+y)+2.5) #broadcasting

A soma das duas matrizes é:
 [[2. 1.]
 [1. 2.]]
A soma com elementos tipo float é:
 [[4.5 3.5]
 [3.5 4.5]]


In [6]:
#subtração
print('A subtração das duas matrizes é:\n', x-y)
print('A subtração das duas matrizes com elementos tipo float é\n', (x-y)-5.5)

A subtração das duas matrizes é:
 [[0. 1.]
 [1. 0.]]
A subtração das duas matrizes com elementos tipo float é
 [[-5.5 -4.5]
 [-4.5 -5.5]]


In [13]:
#divisão
print('A divisão das duas matrizes é:\n', x/y) #retornando um valor "inf" como infinito, pois é uma divisão por zero
print('Uma divisão utilizando elementos tipo float é:\n', x/1.5) #broadcasting

A divisão das duas matrizes é:
 [[ 1. inf]
 [inf  1.]]
Uma divisão utilizando elementos tipo float é:
 [[0.66666667 0.66666667]
 [0.66666667 0.66666667]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [14]:
#quando o broadcasting não funciona
np.array([1,2,3])+np.array([1,2])
#retornará um erro pois há uma inconsistência entre as matrizes, visto que uma 
#possui 3 elementos e a outra possui 2

ValueError: ignored

In [15]:
#subtração, soma, multiplicação, divisão
a=(x+y)/(x*y)-x
print('A =\n', a)

A =
 [[ 1. inf]
 [inf  1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
